import hondashine from '../assets/bikes/shine.jpg';
import himalayan from '../assets/bikes/himalayan.jpg';
import hondacrf from '../assets/bikes/crf.jpg';

const bikeData = [
    {
    id: "1",
    name: 'Honda Shine',
    type: "bike",
    description: "Old Classic bike",
    engineCapacity: "125 cc",
    tankCapacity: "12 liters",
    mileage: "42 km/l",
    gears: "5 gears",
    brake: "Dual drum",
    insurance: "Third party",
    price: 1200,
    trips: 109,
    rating: 4.3,
    // image: "/src/assets/bikes/yamaha-fazer.jpg",
      image: hondashine,
    },
    {

      id: "2",
      name: 'Himalaya',
      type: "bike",
      description: "Touring bike",
      engineCapacity: "400 cc",
      tankCapacity: "12 liters",
      mileage: "42 km/l",
      gears: "5 gears",
      brake: "Dual drum",
      insurance: "Third party",
      price: 1500,
      trips: 109,
      rating: 4.3,
      // image: "/src/assets/bikes/yamaha-fazer.jpg",
        image: himalayan,

        
      },
      {
        id: "3",
        name: 'CRF Rally',
        type: "bike",
        description: "Old Classic bike",
        engineCapacity: "125 cc",
        tankCapacity: "12 liters",
        mileage: "42 km/l",
        gears: "5 gears",
        brake: "Dual drum",
        insurance: "Third party",
        price: 1200,
        trips: 109,
        rating: 4.3,
        // image: "/src/assets/bikes/yamaha-fazer.jpg",
          image: hondacrf,

      },
      {
        id: "4",
        name: 'CRF Rally',
        type: "bike",
        description: "Old Classic bike",
        engineCapacity: "125 cc",
        tankCapacity: "12 liters",
        mileage: "42 km/l",
        gears: "5 gears",
        brake: "Dual drum",
        insurance: "Third party",
        price: 1200,
        trips: 109,
        rating: 4.3,
        // image: "/src/assets/bikes/yamaha-fazer.jpg",
          image: hondacrf,


        name: 'CRF Rally',
        rating: 5.0,
        trips: 30,
        price: 2800,
        image: hondacrf,
      },
      {
        id: "5",
        name: 'Honda Shine',
        type: "bike",
        description: "Old Classic bike",
        engineCapacity: "125 cc",
        tankCapacity: "12 liters",
        mileage: "42 km/l",
        gears: "5 gears",
        brake: "Dual drum",
        insurance: "Third party",
        price: 1200,
        trips: 109,
        rating: 4.3,
        // image: "/src/assets/bikes/yamaha-fazer.jpg",
          image: hondashine,


      },
      {
        id: "6",
        name: 'Honda Shine',
        type: "bike",
        description: "Old Classic bike",
        engineCapacity: "125 cc",
        tankCapacity: "12 liters",
        mileage: "42 km/l",
        gears: "5 gears",
        brake: "Dual drum",
        insurance: "Third party",
        price: 1200,
        trips: 109,
        rating: 4.3,
        // image: "/src/assets/bikes/yamaha-fazer.jpg",
          image: hondacrf,

        name: 'CRF Rally',
        rating: 5.0,
        trips: 30,
        price: 2800,
        image: hondacrf,
      },
      {
        id: "7",
        name: 'Honda Shine',
        type: "bike",
        description: "Old Classic bike",
        engineCapacity: "125 cc",
        tankCapacity: "12 liters",
        mileage: "42 km/l",
        gears: "5 gears",
        brake: "Dual drum",
        insurance: "Third party",
        price: 1200,
        trips: 109,
        rating: 4.3,
        // image: "/src/assets/bikes/yamaha-fazer.jpg",
          image: hondashine,
        
      },
    

];
export default bikeData;
